version: '3.8'

services:
  user_management:
    build: ./user_management
    ports:
      - "8000:8000"
    networks:
      - app_network

  product_catalog:
    build: ./product_catalog
    ports:
      - "8001:8001"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge